name = "ram-roo-thang-bot"
main = "src/index.js"
compatibility_date = "2026-08-21"

[vars]
LIFF_URL = "https://liff.line.me/2011201463-2rdSwrwB"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "CHAT_HISTORY_RAM"
id = "8bd20354236540b59ad64da34f43c6ee"

[[kv_namespaces]]
binding = "BASELINE_DATA"
id = "f14025c3ea9241aaa4b8559eab96b343"

[[kv_namespaces]]
binding = "PARKING_REPORTS"
id = "f69bf1e6461c4627979722c3b45fb5f7"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "2de6b2c154d6455d84aa133a0a61e708"

[[kv_namespaces]]
binding = "STUDENT_SCHEDULES"
id = "819201b7251a4a48a73c0079f04ca005"
